name: Publish to npm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run build script
        run: npm run build

      - name: Configure .npmrc
        run: |
          echo "@ensp1re:registry=https://npm.pkg.github.com/" > ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=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" >> ~/.npmrc

      - name: Publish package
        run: npm publish
        working-directory: ./build
        env:
          NODE_AUTH_TOKEN: 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
